# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41b6cf33c500491fe1ca0f3647d2a5ab9ba210130bb3f530ecfa8d848d247929af320f5b2ccb52f35dbdc1163cc002e913a9a5fdd6ed5c0257e6a077e3c0b25b

test:
  secret_key_base: d809c17280b1952b23a07d2b1768d124ae54774199b459925d088b1da76594d051122a3f5aa044fae057fa9a28ea68a2660afa181b0d2e10c170a7bedbafb2e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
